### ISSUE TITLE
Boot loop ?

### ISSUE THREAD

**Issue by realjax** [HeimdallMidgard/ESP-32-BLE-Scanner#11]
Tried to upload it to my esp32 but I end up with a boot loop..

```
Starting...

deserializeJson() failed: 
EmptyInput
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x4000c52a  PS      : 0x00060330  A0      : 0x800d3879  A1      : 0x3ffccae0  
A2      : 0x3ffc2961  A3      : 0x00000000  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3ffc2974  
A10     : 0x00000000  A11     : 0x3f400314  A12     : 0x00000000  A13     : 0x0000000a  
A14     : 0x00000000  A15     : 0x00000001  SAR     : 0x0000001d  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x4000142d  LEND    : 0x4000143a  LCOUNT  : 0xffffffec  
```

I assume it has something to do with spiffs, something fails there. Build goes ok though, no errors,  just two warnings:

```
Compiling .pio/build/esp32doit-devkit-v1/FrameworkArduino/esp32-hal-touch.c.o
/Users/me/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c: In function 'spiTransferBytesNL':
/Users/me/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c:922:39: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_out8 = &result[c_longs-1];
                                       ^
/Users/me/.platformio/packages/framework-arduinoespressif32/cores/esp32/esp32-hal-spi.c:923:40: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
                 uint8_t * last_data8 = &last_data;
```

Upload also goes fine.

**Comment by realjax** [comment]
Yep, 100% a spiffs problem. When I edit that part out en just use hardcoded vars for the settings.json all is fine. 

well..  that is untill I hit this error continuously on screen :)

```
E NimBLEScan: "Error initiating GAP discovery procedure; rc=3, "
```

**Comment by realjax** [comment]
Turned out to be a problem with PlatformIO. It refused to upload the spiffs. Had to resort to manually upload it which only worked after I fixed several other issues first. Gotta love platformIO :-(

Now it no longer is in a boot loop, but now it displays te one wifi error after the next :-(

**Comment by HeimdallMidgard** [comment]
See other issue.

**Comment by iChenlife** [comment]
> Turned out to be a problem with PlatformIO. It refused to upload the spiffs. Had to resort to manually upload it which only worked after I fixed several other issues first. Gotta love platformIO :-(
> 
> Now it no longer is in a boot loop, but now it displays te one wifi error after the next :-(

I don't know how to solve the same problem. Would you please tell me the detailed modification

**Comment by realjax** [comment]
Try this fork  https://github.com/realjax/ESP-32-BLE-Scanner
